### ISSUE TITLE
开始菜单，选择麒麟软件商店，选择之后无响应，无法打开

### ISSUE THREAD

**Issue by chz0708** [ukui/ukui-menus#9]

**Comment by xiaodongliu-nudt** [comment]
Hi @chz0708 
Thanks for your contribution to UKUI. However this project is deprecated since UKUI3.0. So please feedback your  menu-related bug reports to  [ukui-menu](https://github.com/ukui/ukui-menu).

**Comment by xiaodongliu-nudt** [comment]
This bug is fixed in version 20200314, so closed.
